"""Bornes internes des explorateurs, sans configuration persistante."""

MAX_SOURCE_BYTES = 1024 * 1024
MAX_SOURCE_PATH_LENGTH = 4096
MAX_FILTER_QUERY_LENGTH = 256
MAX_ROUTE_BRANCHES = 64
MAX_SYNTAX_MESSAGE_LENGTH = 240
MAX_TEMPLATE_DEPTH = 8
MAX_VISITED_TEMPLATES = 128

MAX_ENTITY_DIRECTORY_ENTRIES = 4096
MAX_ENTITY_FILES = 256
MAX_ENTITY_RELATIONS = 512
MAX_ENTITY_FIELDS = 256
MAX_ENTITY_PIVOT_FIELDS = 64

# Lecture synchrone du journal runtime, depuis son début.
MAX_DEBUG_EVENTS = 2000
MAX_DEBUG_LINE_BYTES = 64 * 1024
MAX_DEBUG_SCAN_BYTES = 8 * 1024 * 1024

# Diagnostic final inclus ; collections invalidées sans découpage silencieux.
MAX_DEBUG_ISSUES = 2000
MAX_DEBUG_TRACEBACK_FRAMES = 256
MAX_DEBUG_POST_KEYS = 256
MAX_DEBUG_HEADERS = 128
# Caractères Unicode ; jusqu’à 3072 octets de percent-encoding pour 256 emoji.
MAX_DEBUG_EVENT_ID_LENGTH = 256

# Inventaire physique, distinct du suivi des références de Route Explorer.
MAX_TEMPLATE_FILES = 512
MAX_TEMPLATE_DIRECTORY_ENTRIES = 4096
MAX_TEMPLATE_SCAN_DEPTH = 32

# Projection structurelle en mémoire du Template Viewer.
MAX_TEMPLATE_STRUCTURE_NODES = 4096
MAX_TEMPLATE_REFERENCES = 512
MAX_TEMPLATE_BLOCKS = 512
MAX_TEMPLATE_JINJA_TOKENS = 32768
