"""Bornes internes de Route Explorer, sans configuration persistante."""

MAX_SOURCE_BYTES = 1024 * 1024
MAX_SOURCE_PATH_LENGTH = 4096
MAX_FILTER_QUERY_LENGTH = 256
MAX_ROUTE_BRANCHES = 64
MAX_SYNTAX_MESSAGE_LENGTH = 240
MAX_TEMPLATE_DEPTH = 8
MAX_VISITED_TEMPLATES = 128
